sudo: required
language: go
services:
- docker
jobs:
  include:
    - stage: test and build
      script:
      - set -x
      - if [ -z "${DOCKER_REGISTRY}" ] || [ -z "${DOCKER_NAMESPACE}" ] || [ -z "${DOCKER_IMAGE}" ]; then exit 1; fi;
      - echo "DOCKER_REGISTRY=${DOCKER_REGISTRY}" > ./Makefile.properties
      - echo "DOCKER_NAMESPACE=${DOCKER_NAMESPACE}" >> ./Makefile.properties
      - echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> ./Makefile.properties
      - make testc
      - make build
    - stage: release
      if: branch = master
      script:
      - set -x
      - if [ -z "${DOCKER_REGISTRY}" ] || [ -z "${DOCKER_NAMESPACE}" ] || [ -z "${DOCKER_IMAGE}" ]; then exit 1; fi;
      - echo "DOCKER_REGISTRY=${DOCKER_REGISTRY}" > ./Makefile.properties
      - echo "DOCKER_NAMESPACE=${DOCKER_NAMESPACE}" >> ./Makefile.properties
      - echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> ./Makefile.properties
      - git remote set-url origin "$(printf -- "${REPO_HTTPS_URL}" | sed -e "s|https://|https://${REPO_USERNAME}:${REPO_PERSONAL_ACCESS_TOKEN}@|g")"
      - git checkout master
      - make version.bump
      - git push --tags
    - stage: publish
      if: tag = true
      script:
      - docker login "${DOCKER_REGISTRY}" -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}"
      - make dkpublish VERSION="${TRAVIS_TAG}"
      - docker logout
